import { Product } from '../types/product';

// Valentine's Collection – WE do.not CARE CLUB
export const valentinesProducts: Product[] = [
  {
    id: "val-lovebomb-tee",
    name: "Love Bomb Classic Tee",
    handle: "love-bomb-classic-tee",
    category: "Valentines 2025",
    price: 29.99,
    compareAtPrice: 34.99,
    shortDescription: "Soft tee, loud message. A love bomb for people who don't chase.",
    description: "Soft, flattering, and just a little dangerous. The Love Bomb Classic Tee is for the ones who text back on their own schedule. Featuring a bold heart graphic and subtle WE do.not CARE CLUB crown, it's your Valentine's uniform for when you're cute but not clingy.",
    image: "https://d64gsuwffb70l.cloudfront.net/691ba59ffe4554d9faab1ada_1764015126365_3eda6c54.webp",
    gallery: ["https://d64gsuwffb70l.cloudfront.net/691ba59ffe4554d9faab1ada_1764015126365_3eda6c54.webp"],
    tags: ["valentines", "t-shirt", "love bomb", "we do.not care club", "gift for her", "gift for bestie"],
    seoTitle: "Love Bomb Classic Tee – Valentine's Shirt | WE do.not CARE CLUB",
    seoDescription: "Shop the Love Bomb Classic Tee – a bold, soft Valentine's Day shirt for women who don't chase. Perfect gift for her, besties, and situationships.",
    sizes: ["XS", "S", "M", "L", "XL", "2XL"],
    sizeChart: [
      { size: "XS", chest: "31–33 in", length: "27 in" },
      { size: "S",  chest: "34–36 in", length: "28 in" },
      { size: "M",  chest: "37–39 in", length: "29 in" },
      { size: "L",  chest: "40–42 in", length: "30 in" },
      { size: "XL", chest: "43–45 in", length: "31 in" },
      { size: "2XL", chest: "46–48 in", length: "32 in" },
    ],
    inventoryBySize: { XS: 8, S: 12, M: 15, L: 15, XL: 10, "2XL": 6 },
    gradient: 'from-pink-300 via-rose-400 to-red-500',
  },
  {
    id: "val-heartbreaker-hoodie",
    name: "Heartbreaker Energy Hoodie",
    handle: "heartbreaker-energy-hoodie",
    category: "Valentines 2025",
    price: 59.0,
    compareAtPrice: 69.0,
    shortDescription: "Oversized, cozy, and a walking red flag in the best way.",
    description: "For the girlies who soft-launch then vanish. The Heartbreaker Energy Hoodie is oversized, fleece-lined, and covered in quiet flex. Front chest print keeps it low-key; back print lets them know this heart doesn't beg.",
    image: "https://d64gsuwffb70l.cloudfront.net/691ba59ffe4554d9faab1ada_1764015131479_5a499ce4.webp",
    gallery: ["https://d64gsuwffb70l.cloudfront.net/691ba59ffe4554d9faab1ada_1764015131479_5a499ce4.webp"],
    tags: ["valentines hoodie", "heartbreaker", "oversized hoodie", "cozy", "we do.not care club"],
    seoTitle: "Heartbreaker Energy Hoodie – Anti-Valentine Hoodie",
    seoDescription: "Heartbreaker Energy Hoodie – oversized, cozy Valentine's hoodie for the unapologetic heartbreaker.",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
    inventoryBySize: { S: 10, M: 14, L: 16, XL: 12, "2XL": 8, "3XL": 5 },
    gradient: 'from-red-600 via-rose-700 to-pink-800',
  },
];
